version: '3'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3381:3306"
  php:
    build: ./setup/php
    volumes:
      - ./project-laravel:/var/www/html/project
      - ./setup:/var/www/setup
      - ./setup/docker.conf:/usr/local/etc/php-fpm.d/docker.conf
      - ./setup/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - db
    command: bash -c "chown -R www-data:www-data /var/www && chmod +x /var/www/setup/php/runphp.sh && bash /var/www/setup/php/runphp.sh"
  nginx:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./setup/default.conf:/etc/nginx/conf.d/default.conf
      - ./project-laravel/public:/var/www/html
    depends_on:
      - php
  ng:
    image: node:8
    volumes:
      - ./project-angular:/usr/src/app
    ports:
      - "8082:4200"
    command: bash -c "cd /usr/src/app && npm i && npm start"
